development:
  adapter: postgresql
  encoding: unicode
  database: bus_locator_development
  pool: 5
  username: bus_locator
  password: passwords

test:
  adapter: postgresql
  encoding: unicode
  database: bus_locator_test
  pool: 5
  username: bus_locator
  password: passwords

production:
  adapter: postgresql
  encoding: unicode
  database: bus_locator_production
  pool: 5
  username: bus_locator
  password: passwords